apiVersion: v1
kind: Service
metadata:
  name: bcse-service
  labels:
    app: bcse
spec:
  type: NodePort
  selector:
    app: bcse
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 
